services:
  - type: web
    name: stockpredict-mvp-ml
    env: python
    plan: free
    buildCommand: "pip install --upgrade pip setuptools wheel && pip install -r requirements.txt"
    startCommand: "streamlit run app/main.py --server.port $PORT --server.address 0.0.0.0"
    autoDeploy: true
